title: Fikry Nuhuman
# logo: /assets/img/headshot_circle.png
description: Machine Learning based Medical Research | Micrososft Azure | Full Stack Web & Flutter Developer | CS50x(Harvard) Certified | Maths & Science enthusiast
# show_downloads: true
theme: jekyll-theme-minimal
